namespace Rd.BlazorIcon.BootstrapIcons
{
      /// <summary>
      ///   This file was generated by Rd.BlazorIcon.IconSetBuilder
      ///   License: Licensed under MIT (https://github.com/RDDelValle/Rd.BlazorIcon/blob/main/LICENSE)
      ///   Generated On: 10/13/2024 at 20:34:14.3554980
      ///   Vendor: Bootstrap Icons v1.11.3 (https://icons.getbootstrap.com/)
      ///   Vendor Source: node_modules/bootstrap-icons/icons/(https://github.com/twbs/icons/)
      ///   Vendor Copyright: Copyright 2019-2024 The Bootstrap Authors
      ///   Vendor License: Licensed under MIT (https://github.com/twbs/icons/blob/main/LICENSE)
      /// </summary>

      public partial class BootstrapIcons
       {
// SomeContent
       }

}

