using System.Text;

namespace Rd.BlazorIcon.IconSetBuilder.Utilities;

public class DocsBlockBuilder
{
    private readonly StringBuilder _builder = new();
    public string? VendorSource { get; set; }
    public string? VendorName { get; set; }
    public string? VendorCopyright { get; set; }
    public string? VendorLicense { get; set; }
    public override string ToString()
    {
        _builder.AppendLine($"      /// <summary>");
        _builder.AppendLine($"      ///   This file was generated by Rd.BlazorIcon.IconSetBuilder");
        _builder.AppendLine($"      ///   License: Licensed under MIT (https://github.com/RDDelValle/Rd.BlazorIcon/blob/main/LICENSE)");
        _builder.AppendLine($"      ///   Generated On: {DateTime.Now.ToShortDateString()} at {DateTime.Now.TimeOfDay}");
        
        if(!string.IsNullOrWhiteSpace(VendorName))
            _builder.AppendLine($"      ///   Vendor: {VendorName}");
        if(!string.IsNullOrWhiteSpace(VendorSource))
            _builder.AppendLine($"      ///   Vendor Source: {VendorSource}");
        if(!string.IsNullOrWhiteSpace(VendorCopyright))
            _builder.AppendLine($"      ///   Vendor Copyright: {VendorCopyright}");
        if(!string.IsNullOrWhiteSpace(VendorLicense))
            _builder.AppendLine($"      ///   Vendor License: {VendorLicense}");
        _builder.AppendLine($"      /// </summary>");
        return _builder.ToString();
    }
}